mqtt_client:
  ros__parameters:
    broker:
      host: localhost
      port: 1883
    bridge:
      ros2mqtt:
        ros_topic: /test_topicmain
        mqtt_topic: test_topic_mqtt_main/ros
      mqtt2ros:
        mqtt_topic: test_topic_mqtt_relay/ros
        ros_topic: /test_topicrelay
