mqtt_client:
  ros__parameters:
    broker:
      host: localhost
      port: 1883
    bridge:
      ros2mqtt:
        ros_topic: /test_topicmain_Array4k
        mqtt_topic: test_topic_mqtt_main/ros_Array4k
      mqtt2ros:
        mqtt_topic: test_topic_mqtt_relay/ros_Array4k
        ros_topic: /test_topicrelay_Array4k
