mqtt_client:
  ros__parameters:
    broker:
      host: 192.168.2.3
      port: 1883
    bridge:
      ros2mqtt:
        ros_topic: /test_topicmain_Array64k
        mqtt_topic: test_topic_mqtt_main/ros_Array64k
      mqtt2ros:
        mqtt_topic: test_topic_mqtt_relay/ros_Array64k
        ros_topic: /test_topicrelay_Array64k
