mqtt_client:
  ros__parameters:
    broker:
      host: 192.168.2.3
      port: 1883
    bridge:
      ros2mqtt:
        ros_topic: /test_topicmain_PointCloud512k
        mqtt_topic: test_topic_mqtt_main/ros_PointCloud512k
      mqtt2ros:
        mqtt_topic: test_topic_mqtt_relay/ros_PointCloud512k
        ros_topic: /test_topicrelay_PointCloud512k
